// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkdqetrsnlpwexnogbtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrZHFldHJzbmxwd2V4bm9nYnR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODE4ODIsImV4cCI6MjA3MTM1Nzg4Mn0.SyLf43wKKDXWTZHK4LpdJl3qbgJp8l7WJIVrGKKsK3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});